In [1]:
import numpy as np

# Bài 1: Làm quen với cú pháp

In [2]:
# ndarray: Mảng N chiều, kiểu dữ liệu đồng nhất
arr = np.array([1, 2, 3, 4])
matrix = np.array([[1, 2], [3, 4], [5, 6]])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
matrix

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
# Shape: Kích thước các chiều của mảng (ví dụ: (3,4))
print(arr.shape)
print(matrix.shape)

(4,)
(3, 2)


In [6]:
# Dtype: Kiểu dữ liệu của phần tử (float32, int64,...)
print(arr.dtype)
float_arr = np.array([1.0, 2.0], dtype = np.float32)
print(float_arr.dtype)

int32
float32


In [7]:
# Tạo mảng: np.array(), np.zeros(), np.ones(), np.arange(), np.linspace()
zeros = np.zeros((3, 4)) # Mảng 3x4 toàn 0
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
ones = np.ones((4,)) # Mảng 4 phần tử toàn 1
ones

array([1., 1., 1., 1.])

In [9]:
range_arr = np.arange(0, 10, 3) # [0, 3, 6, 9] (start, stop, step)
range_arr

array([0, 3, 6, 9])

In [10]:
lin_arr = np.linspace(0, 2, 6) # (start, stop, num)
lin_arr

array([0. , 0.4, 0.8, 1.2, 1.6, 2. ])

In [11]:
# Truy cập và thay đổi phần tử: Slicing, Indexing
arr = np.array([1, 2, 3, 4, 5])
print(arr[1])      # Truy cập phần tử
print(arr[1:4])    # slicing
arr[2] = 8         # Thay đổi phần tử
print(arr)

matrix = np.array([[30, 4], [19, 75]])
print(matrix[0, 1]) # Truy cập phần tử 2D

2
[2 3 4]
[1 2 8 4 5]
4


In [12]:
# Các phép toán trên mảng: Cộng, trừ, nhân, chia, ma trận
a = np.array([3, 0, 4])
b = np.array([7, 5, 1])

print(f"Cộng từng phần tử: {a + b}") 
print(f"Nhân từng phần tử: {a * b}") 
print(f"Tích vô hướng: {a @ b}") 

# Phép nhân ma trận
mat1 = np.array([[3, 4], [7, 5]])
mat2 = np.array([[7, 5], [5, 4]])
print(np.dot(mat1, mat2))

Cộng từng phần tử: [10  5  5]
Nhân từng phần tử: [21  0  4]
Tích vô hướng: 25
[[41 31]
 [74 55]]


In [13]:
# Hàm thống kê: mean(), sum(), min(), max(), std()
data = np.array([3, 0, 4, 1, 9, 7, 5])
print(f"trung bình: {np.mean(data)}")
print(f"tổng: {np.sum(data)}")
print(f"giá trị lớn nhất: {np.max(data)}")
print(f"độ lệch chuẩn: {np.std(data)}")

trung bình: 4.142857142857143
tổng: 29
giá trị lớn nhất: 9
độ lệch chuẩn: 2.9485382057928993


In [14]:
# Thao tác với hình dạng mảng: reshape(), flatten(), transpose()
arr = np.arange(8)
print(f"arange: {arr}")
matrix = arr.reshape(2, 4)
print(f"reshape: {matrix}")
flat = matrix.flatten()
print(f"flatten: {flat}")
transposed = matrix.T
print(f"transposed: {transposed}")

arange: [0 1 2 3 4 5 6 7]
reshape: [[0 1 2 3]
 [4 5 6 7]]
flatten: [0 1 2 3 4 5 6 7]
transposed: [[0 4]
 [1 5]
 [2 6]
 [3 7]]


# Bài 2: Sử dụng np.where()

In [15]:
# Thay các số âm bằng 0
arr = np.array([1, -2, 3, -4, 5, -6])
print(np.where(arr < 0, 0, arr))

[1 0 3 0 5 0]


In [16]:
# Thay số chẵn bằng "even", số lẻ bằng "odd"
# np.where(condition, value_if_true, value_if_false)
print(np.where(arr % 2 == 0, "even", "odd"))

['odd' 'even' 'odd' 'even' 'odd' 'even']


In [17]:
# Tìm vị trí các phần tử > 2
print(np.where(arr > 2)[0])

[2 4]


# Bài 3: Kết hợp nhiều điều kiện

In [18]:
temps = np.array([25, 28, 30, 22, 35, 18, 20])

conditions = [
    temps < 20,
    (temps >= 20) & (temps <= 29),
    temps >= 30
]

weather = ["Cold", "Mid", "Hot"] 

print(np.select(conditions, weather, default=0))

['Mid' 'Mid' 'Hot' 'Mid' 'Hot' 'Cold' 'Mid']


# Bài 4: Áp dụng hàm theo trục

In [19]:
mat = np.random.randint(1, 100, (5, 5))
mat

array([[10, 79, 27, 47, 63],
       [97, 27, 72, 86, 25],
       [21, 43,  5, 82, 27],
       [77, 16, 69, 83, 25],
       [98, 73,  4, 81, 98]])

In [20]:
# Chuẩn hóa từng hàng (trừ đi min, chia cho max - min)
def normalize_rows(mat):
    row_min = mat.min(axis=1, keepdims=True)
    row_max = mat.max(axis=1, keepdims=True)
    return np.where(row_max - row_min == 0, 0, (mat - row_min) / (row_max - row_min))

print(normalize_rows(mat))

[[0.         1.         0.24637681 0.53623188 0.76811594]
 [1.         0.02777778 0.65277778 0.84722222 0.        ]
 [0.20779221 0.49350649 0.         1.         0.28571429]
 [0.91044776 0.         0.79104478 1.         0.13432836]
 [1.         0.73404255 0.         0.81914894 1.        ]]


In [21]:
# Áp dụng hàm softmax theo cột
def normalize_cols(mat):
    exp_x = np.exp(mat - np.max(mat, axis=0, keepdims=True)) # Tránh tràn số
    return exp_x / np.sum(exp_x, axis=0, keepdims=True) # Hàm softmax

print(normalize_cols(mat))

[[4.42626865e-39 9.97527377e-01 2.72676114e-20 1.07441267e-17
  6.30511676e-16]
 [2.68941421e-01 2.60382483e-23 9.52574127e-01 9.30370466e-01
  1.97925988e-32]
 [2.65019037e-34 2.31378752e-16 7.60621319e-30 1.70403295e-02
  1.46248623e-31]
 [5.54329585e-10 4.34883033e-28 4.74258732e-02 4.63204180e-02
  1.97925988e-32]
 [7.31058578e-01 2.47262316e-03 2.79816946e-30 6.26878689e-03
  1.00000000e+00]]


# Bài 5: Xử lý dữ liệu phức tạp

In [22]:
data = np.array([
    [1, 2, np.nan],
    [4, np.nan, 6],
    [7, 8, 9]
])

data

array([[ 1.,  2., nan],
       [ 4., nan,  6.],
       [ 7.,  8.,  9.]])

In [23]:
# Thay các giá trị NaN bằng trung bình cột
data = np.where(np.isnan(data), np.nanmean(data), data)
data

array([[1.        , 2.        , 5.28571429],
       [4.        , 5.28571429, 6.        ],
       [7.        , 8.        , 9.        ]])

In [24]:
# Tính z-score cho mỗi cột (z-score = (mattrix - mean) / std)
def z_score(mat):
    mean = np.mean(mat, axis=0, keepdims=True)
    std = np.std(mat, axis=0, keepdims=True)
    return (mat - mean) / std

z_score(data)

array([[-1.22474487, -1.26171974, -0.91733643],
       [ 0.        ,  0.07764429, -0.47346396],
       [ 1.22474487,  1.18407545,  1.3908004 ]])

In [25]:
# Chuẩn hóa min-max theo cột
normalize_rows(data)

array([[0.        , 0.23333333, 1.        ],
       [0.        , 0.64285714, 1.        ],
       [0.        , 0.5       , 1.        ]])